const teste = 'teste'

try {
    teste = 'new teste'
} catch (error) {
    console.log(error)
}

console.log("Continua executando..........")